### ISSUE TITLE
Find out what is causing the current shield to not work as intended

### ISSUE THREAD

**Issue by Maggedelle** [Maggedelle/Reinforcement-Learning-for-Drone-Navigation-and-Pump-Localization#46]

**Comment by Sandborg** [comment]
Currently, it seems like the shield function does not function as inteded, allowing moves that appears to be too dangerous.

A hint might be to compare the shield function in uppaal to the function in python.

**Comment by Maggedelle** [comment]
this issue has been fixed in #50
